name: Frontend Deployment

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      # Build Next.js di GitHub agar server kamu ringan
      - name: Install dependencies
        run: npm install

      - name: Build Next.js
        run: npm run build

      # Prepare SSH access
      - name: Add server to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H "${{ secrets.SERVER_IP }}" >> ~/.ssh/known_hosts

      - name: Setup SSH key
        run: |
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

      # Upload the app EXCEPT node_modules
      - name: Upload frontend to server
        run: |
          rsync -avz --delete \
          --exclude="node_modules" \
          --exclude=".git" \
          --exclude=".env" \
          -e "ssh -i ~/.ssh/id_ed25519" \
          ./  ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/var/www/idshopcase/frontend/

      # Install server dependencies & restart PM2
      - name: Install & Restart PM2
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /var/www/idshopcase/frontend/
            npm install --production=false

            pm2 restart idshopcase-frontend || pm2 start npm --name "idshopcase-frontend" -- start
            pm2 save
